DROP FUNCTION check_stmt_cnt(sserver_id integer, start_id integer, end_id integer);
DROP FUNCTION check_stmt_cnt_all_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION check_stmt_cnt_first_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION check_stmt_cnt_second_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION cluster_stats_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION cluster_stats_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION cluster_stats_reset_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION cluster_stats_reset_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION collect_queries(userid oid, datid oid, queryid bigint);
DROP FUNCTION dbagg_jit_stats_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION dbagg_jit_stats_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION dbstats_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION dbstats_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION dbstats_reset_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION dbstats_reset_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION dbstats_sessions_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION dbstats_sessions_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION func_top_calls_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION func_top_calls_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION func_top_time_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION func_top_time_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION func_top_trg_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION func_top_trg_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION ix_top_fetch_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION ix_top_fetch_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION ix_top_io_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION ix_top_io_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION ix_unused_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION report_queries(report_context jsonb, sserver_id integer);
DROP FUNCTION settings_and_changes_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION settings_and_changes_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION statements_stats_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION statements_stats_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION tablespaces_stats_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION tablespaces_stats_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION tbl_top_dead_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION tbl_top_fetch_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION tbl_top_fetch_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION tbl_top_io_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION tbl_top_io_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION tbl_top_mods_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION template_populate_sections(report_context jsonb, sserver_id integer, template text, report_id integer);
DROP FUNCTION top_analyzed_tables_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_analyzed_tables_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_cpu_time_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_cpu_time_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_dml_tables_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_dml_tables_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_elapsed_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_elapsed_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_exec_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_exec_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_exec_time_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_exec_time_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_growth_indexes_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_growth_indexes_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_growth_tables_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_growth_tables_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_io_filesystem_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_io_filesystem_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_iowait_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_iowait_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_jit_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_jit_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_plan_time_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_plan_time_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_scan_tables_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_scan_tables_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_shared_blks_fetched_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_shared_blks_fetched_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_shared_dirtied_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_shared_dirtied_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_shared_reads_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_shared_reads_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_shared_written_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_shared_written_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_temp_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_temp_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_upd_vac_tables_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_upd_vac_tables_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_vacuumed_indexes_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_vacuumed_indexes_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_vacuumed_tables_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_vacuumed_tables_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_wait_sampling_events_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_wait_sampling_events_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_wal_size_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION top_wal_size_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION wait_sampling_totals_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION wait_sampling_totals_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION wal_stats_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION wal_stats_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION wal_stats_reset_diff_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION wal_stats_reset_htbl(report_context jsonb, sserver_id integer);
DROP FUNCTION cluster_stats(sserver_id integer, start_id integer, end_id integer);
DROP FUNCTION collect_obj_stats(properties jsonb, sserver_id integer, s_id integer, skip_sizes boolean);
DROP FUNCTION collect_pg_stat_statements_stats(properties jsonb, sserver_id integer, s_id integer, topn integer);
DROP FUNCTION collect_pg_wait_sampling_stats_11(properties jsonb, sserver_id integer, s_id integer, topn integer);
DROP FUNCTION get_diffreport(sserver_id integer, start1_id integer, end1_id integer, start2_id integer, end2_id integer, description text, with_growth boolean);
DROP FUNCTION get_report(sserver_id integer, start_id integer, end_id integer, description text, with_growth boolean);
DROP FUNCTION get_report_context(sserver_id integer, start1_id integer, end1_id integer, description text, start2_id integer, end2_id integer);
DROP FUNCTION init_report_temp_tables(report_context jsonb, sserver_id integer);
DROP FUNCTION sample_dbobj_delta(properties jsonb, sserver_id integer, s_id integer, topn integer, skip_sizes boolean);
DROP FUNCTION save_pg_stat_statements(sserver_id integer, s_id integer);
DROP FUNCTION show_servers();
DROP FUNCTION statements_stats(sserver_id integer, start_id integer, end_id integer, topn integer);
DROP FUNCTION take_sample(sserver_id integer, skip_sizes boolean);
DROP FUNCTION take_sample(server name, skip_sizes boolean);
DROP FUNCTION take_sample_subset;
DROP FUNCTION top_io_indexes(sserver_id integer, start_id integer, end_id integer);
DROP FUNCTION top_io_tables(sserver_id integer, start_id integer, end_id integer);
DROP FUNCTION top_kcache_statements(sserver_id integer, start_id integer, end_id integer);
DROP FUNCTION top_statements(sserver_id integer, start_id integer, end_id integer);
DROP FUNCTION cluster_stats_reset(sserver_id integer, start_id integer, end_id integer);
DROP FUNCTION dbstats_reset(sserver_id integer, start_id integer, end_id integer);
DROP FUNCTION cleanup_report_temp_tables(report_context jsonb, sserver_id integer);
DROP FUNCTION dbstats_sessions(sserver_id integer, start_id integer, end_id integer, topn integer);
DROP FUNCTION top_functions(sserver_id integer, start_id integer, end_id integer, trigger_fn boolean);
DROP FUNCTION dbstats;
DROP FUNCTION profile_checkavail_functions;
DROP FUNCTION profile_checkavail_trg_functions;
DROP FUNCTION settings_and_changes;
DROP FUNCTION top_indexes;
DROP FUNCTION top_tables;
DROP FUNCTION wal_stats;
DROP FUNCTION jsonb_replace;
DROP FUNCTION create_server_partitions;
DROP FUNCTION mark_pg_stat_statements;
