DROP FUNCTION collect_obj_stats;
DROP FUNCTION get_report_context;
DROP FUNCTION import_data;
DROP FUNCTION import_section_data_profile;
DROP FUNCTION import_section_data_subsample;
DROP FUNCTION init_sample;
DROP FUNCTION sample_dbobj_delta;
DROP FUNCTION take_sample(integer, boolean);
DROP FUNCTION take_sample(name, boolean);
DROP FUNCTION take_sample_subset(integer, integer);
DROP FUNCTION top_tables;
DROP FUNCTION top_toasts;
DROP FUNCTION take_subsample(integer, jsonb);
