DROP FUNCTION drop_server;
DROP FUNCTION delete_samples(integer, integer, integer);
DROP FUNCTION collect_obj_stats;
DROP FUNCTION collect_pg_stat_statements_stats;
DROP FUNCTION create_server(name, text, boolean, integer, text);
DROP FUNCTION export_data;
DROP FUNCTION import_data;
DROP FUNCTION take_sample(integer, boolean);
DROP FUNCTION get_report_context;
DROP FUNCTION save_pg_stat_statements;
DROP FUNCTION statements_stats;
DROP FUNCTION top_statements;
DROP FUNCTION top_elapsed_htbl;
DROP FUNCTION top_elapsed_diff_htbl;
DROP FUNCTION top_exec_time_diff_htbl;
DROP FUNCTION top_exec_time_htbl;
DROP FUNCTION top_plan_time_diff_htbl;
DROP FUNCTION top_plan_time_htbl;
