DROP FUNCTION create_server;
DROP FUNCTION create_server_partitions;
DROP FUNCTION drop_server(name);
DROP FUNCTION export_data;
DROP FUNCTION get_report_context;
DROP FUNCTION get_report_datasets;
DROP FUNCTION import_data;
DROP FUNCTION import_section_data_profile;
DROP FUNCTION init_sample;
DROP FUNCTION profile_checkavail_walstats;
DROP FUNCTION report_queries_format;
DROP FUNCTION take_sample(integer, boolean);
DROP FUNCTION settings_format;
DROP FUNCTION settings_format_diff;
