/* ===== import queries update ===== */
INSERT INTO import_queries_version_order VALUES
  ('pg_profile','3.7','pg_profile','0.3.6');

ALTER TABLE sample_stat_database
  ADD COLUMN checksum_failures      bigint,
  ADD COLUMN checksum_last_failure timestamp with time zone
;

ALTER TABLE last_stat_database
  ADD COLUMN checksum_failures      bigint,
  ADD COLUMN checksum_last_failure timestamp with time zone
;

UPDATE import_queries SET query =
  'INSERT INTO sample_stat_database (server_id,sample_id,datid,datname,'
    'xact_commit,xact_rollback,blks_read,blks_hit,tup_returned,tup_fetched,'
    'tup_inserted,tup_updated,tup_deleted,conflicts,temp_files,temp_bytes,'
    'deadlocks,checksum_failures,checksum_last_failure,blk_read_time,'
    'blk_write_time,stats_reset,datsize,'
    'datsize_delta,datistemplate,session_time,active_time,'
    'idle_in_transaction_time,sessions,sessions_abandoned,sessions_fatal,'
    'sessions_killed)'
  'SELECT '
    'srv_map.local_srv_id, '
    'dt.sample_id, '
    'dt.datid, '
    'dt.datname, '
    'dt.xact_commit, '
    'dt.xact_rollback, '
    'dt.blks_read, '
    'dt.blks_hit, '
    'dt.tup_returned, '
    'dt.tup_fetched, '
    'dt.tup_inserted, '
    'dt.tup_updated, '
    'dt.tup_deleted, '
    'dt.conflicts, '
    'dt.temp_files, '
    'dt.temp_bytes, '
    'dt.deadlocks, '
    'dt.checksum_failures, '
    'dt.checksum_last_failure, '
    'dt.blk_read_time, '
    'dt.blk_write_time, '
    'dt.stats_reset, '
    'dt.datsize, '
    'dt.datsize_delta, '
    'dt.datistemplate, '
    'dt.session_time, '
    'dt.active_time, '
    'dt.idle_in_transaction_time, '
    'dt.sessions, '
    'dt.sessions_abandoned, '
    'dt.sessions_fatal, '
    'dt.sessions_killed '
  'FROM %1$s imp '
    'CROSS JOIN json_to_record(imp.row_data) AS '
      'dt ( '
        'server_id       integer, '
        'sample_id       integer, '
        'datid           oid, '
        'datname         name, '
        'xact_commit     bigint, '
        'xact_rollback   bigint, '
        'blks_read       bigint, '
        'blks_hit        bigint, '
        'tup_returned    bigint, '
        'tup_fetched     bigint, '
        'tup_inserted    bigint, '
        'tup_updated     bigint, '
        'tup_deleted     bigint, '
        'conflicts       bigint, '
        'temp_files      bigint, '
        'temp_bytes      bigint, '
        'deadlocks       bigint, '
        'blk_read_time   double precision, '
        'blk_write_time  double precision, '
        'stats_reset     timestamp with time zone, '
        'datsize         bigint, '
        'datsize_delta   bigint, '
        'datistemplate   boolean, '
        'session_time    double precision, '
        'active_time     double precision, '
        'idle_in_transaction_time  double precision, '
        'sessions        bigint, '
        'sessions_abandoned  bigint, '
        'sessions_fatal      bigint, '
        'sessions_killed     bigint, '
        'checksum_failures   bigint, '
        'checksum_last_failure timestamp with time zone'
      ') '
    'JOIN tmp_srv_map srv_map ON '
      '(srv_map.imp_srv_id = dt.server_id) '
    'LEFT OUTER JOIN sample_stat_database ld ON '
      '(ld.server_id = srv_map.local_srv_id AND ld.sample_id = dt.sample_id AND ld.datid = dt.datid) '
  'WHERE ld.server_id IS NULL AND imp.section_id = $1 '
WHERE (extension, from_version, exec_order, relname) =
  ('pg_profile','0.3.1', 1,'sample_stat_database')
;

UPDATE import_queries SET query =
  'INSERT INTO last_stat_database (server_id,sample_id,datid,datname,xact_commit,'
    'xact_rollback,blks_read,blks_hit,tup_returned,tup_fetched,tup_inserted,'
    'tup_updated,tup_deleted,conflicts,temp_files,temp_bytes,deadlocks,'
    'checksum_failures,checksum_last_failure,'
    'blk_read_time,blk_write_time,stats_reset,datsize,datsize_delta,datistemplate,'
    'session_time,active_time,'
    'idle_in_transaction_time,sessions,sessions_abandoned,sessions_fatal,'
    'sessions_killed)'
  'SELECT '
    'srv_map.local_srv_id, '
    'dt.sample_id, '
    'dt.datid, '
    'dt.datname, '
    'dt.xact_commit, '
    'dt.xact_rollback, '
    'dt.blks_read, '
    'dt.blks_hit, '
    'dt.tup_returned, '
    'dt.tup_fetched, '
    'dt.tup_inserted, '
    'dt.tup_updated, '
    'dt.tup_deleted, '
    'dt.conflicts, '
    'dt.temp_files, '
    'dt.temp_bytes, '
    'dt.deadlocks, '
    'dt.checksum_failures, '
    'dt.checksum_last_failure, '
    'dt.blk_read_time, '
    'dt.blk_write_time, '
    'dt.stats_reset, '
    'dt.datsize, '
    'dt.datsize_delta, '
    'dt.datistemplate, '
    'dt.session_time, '
    'dt.active_time, '
    'dt.idle_in_transaction_time, '
    'dt.sessions, '
    'dt.sessions_abandoned, '
    'dt.sessions_fatal, '
    'dt.sessions_killed '
  'FROM %1$s imp '
    'CROSS JOIN json_to_record(imp.row_data) AS '
      'dt ( '
        'server_id       integer, '
        'sample_id       integer, '
        'datid           oid, '
        'datname         name, '
        'xact_commit     bigint, '
        'xact_rollback   bigint, '
        'blks_read       bigint, '
        'blks_hit        bigint, '
        'tup_returned    bigint, '
        'tup_fetched     bigint, '
        'tup_inserted    bigint, '
        'tup_updated     bigint, '
        'tup_deleted     bigint, '
        'conflicts       bigint, '
        'temp_files      bigint, '
        'temp_bytes      bigint, '
        'deadlocks       bigint, '
        'blk_read_time   double precision, '
        'blk_write_time  double precision, '
        'stats_reset     timestamp with time zone, '
        'datsize         bigint, '
        'datsize_delta   bigint, '
        'datistemplate   boolean, '
        'session_time    double precision, '
        'active_time     double precision, '
        'idle_in_transaction_time  double precision, '
        'sessions        bigint, '
        'sessions_abandoned  bigint, '
        'sessions_fatal      bigint, '
        'sessions_killed     bigint, '
        'checksum_failures   bigint, '
        'checksum_last_failure timestamp with time zone'
      ') '
    'JOIN tmp_srv_map srv_map ON '
      '(srv_map.imp_srv_id = dt.server_id) '
    'LEFT OUTER JOIN last_stat_database ld ON '
      '(ld.server_id = srv_map.local_srv_id AND ld.sample_id = dt.sample_id AND ld.datid = dt.datid) '
  'WHERE ld.server_id IS NULL AND imp.section_id = $1 '
WHERE (extension, from_version, exec_order, relname) =
  ('pg_profile','0.3.1', 1,'last_stat_database');
