ALTER TABLE sample_statements
  DROP CONSTRAINT fk_stmt_list;

ALTER TABLE stmt_list
  RENAME TO stmt_list_old;
ALTER TABLE stmt_list_old RENAME CONSTRAINT pk_stmt_list TO pk_stmt_list_old;

CREATE TEMPORARY TABLE queryid_map(
    server_id,
    queryid_md5_old,
    queryid_md5_new
)
AS SELECT DISTINCT
  server_id,
  queryid_md5,
  md5(sl.query)
FROM
  sample_statements s
  JOIN stmt_list_old sl USING (server_id,queryid_md5);

CREATE TABLE stmt_list(
    server_id      integer NOT NULL REFERENCES servers(server_id) ON DELETE CASCADE,
    queryid_md5    char(32),
    query          text,
    CONSTRAINT pk_stmt_list PRIMARY KEY (server_id, queryid_md5)
);
COMMENT ON TABLE stmt_list IS 'Statements, captured in samples';

INSERT INTO stmt_list(
  server_id,
  queryid_md5,
  query
)
SELECT DISTINCT
  server_id,
  md5(query),
  query
FROM stmt_list_old;

DROP TABLE stmt_list_old;

ALTER TABLE sample_statements ALTER COLUMN queryid_md5 SET DATA TYPE char(32);
ALTER TABLE sample_kcache ALTER COLUMN queryid_md5 SET DATA TYPE char(32);

UPDATE sample_kcache s
SET queryid_md5 = map.queryid_md5_new
FROM queryid_map map
WHERE (s.server_id, s.queryid_md5) = (map.server_id, map.queryid_md5_old);

UPDATE sample_statements s
SET queryid_md5 = map.queryid_md5_new
FROM queryid_map map
WHERE (s.server_id, s.queryid_md5 ) = (map.server_id, map.queryid_md5_old);

DROP TABLE queryid_map;

ALTER TABLE sample_statements
  ADD CONSTRAINT fk_stmt_list FOREIGN KEY (server_id,queryid_md5)
    REFERENCES stmt_list (server_id,queryid_md5) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE sample_kcache
  ADD CONSTRAINT fk_kcache_stmt_list FOREIGN KEY (server_id,queryid_md5)
    REFERENCES stmt_list (server_id,queryid_md5) ON DELETE RESTRICT ON UPDATE CASCADE;

DROP VIEW v_sample_stat_tables_interpolated;
DROP VIEW v_sample_stat_indexes_interpolated;

INSERT INTO import_queries_version_order VALUES
  ('pg_profile','0.3.2','pg_profile','0.3.1');

DELETE FROM import_queries
WHERE (extension,from_version) = ('pg_profile','0.3.1')
  AND relname IN ('stmt_list','sample_statements','sample_kcache');

INSERT INTO import_queries VALUES
('pg_profile','0.3.2', 1,'stmt_list',
  'INSERT INTO stmt_list (server_id,queryid_md5,query)'
  'SELECT '
    'srv_map.local_srv_id, '
    'dt.queryid_md5, '
    'dt.query '
  'FROM %1$s imp '
    'CROSS JOIN json_to_record(imp.row_data) AS '
      'dt ( '
        'server_id    integer, '
        'queryid_md5  character(32), '
        'query        text '
      ') '
    'JOIN jsonb_to_recordset($1) AS '
      'srv_map ( '
        'imp_srv_id    integer, '
        'local_srv_id  integer '
      ') ON '
      '(srv_map.imp_srv_id = dt.server_id) '
    'LEFT OUTER JOIN stmt_list ld ON '
      '(ld.server_id = srv_map.local_srv_id AND ld.queryid_md5 = dt.queryid_md5) '
  'WHERE ld.server_id IS NULL AND imp.section_id = $2 '
),
('pg_profile','0.3.2', 1,'sample_statements',
  'INSERT INTO sample_statements (server_id,sample_id,userid,datid,queryid,queryid_md5,'
    'plans,total_plan_time,min_plan_time,max_plan_time,mean_plan_time,stddev_plan_time,'
    'calls,total_exec_time,min_exec_time,max_exec_time,mean_exec_time,stddev_exec_time,'
    'rows,shared_blks_hit,shared_blks_read,shared_blks_dirtied,shared_blks_written,'
    'local_blks_hit,local_blks_read,local_blks_dirtied,local_blks_written,'
    'temp_blks_read,temp_blks_written,blk_read_time,blk_write_time,wal_records,'
    'wal_fpi,wal_bytes)'
  'SELECT '
    'srv_map.local_srv_id, '
    'dt.sample_id, '
    'dt.userid, '
    'dt.datid, '
    'dt.queryid, '
    'dt.queryid_md5, '
    'dt.plans, '
    'dt.total_plan_time, '
    'dt.min_plan_time, '
    'dt.max_plan_time, '
    'dt.mean_plan_time, '
    'dt.stddev_plan_time, '
    'dt.calls, '
    'dt.total_exec_time, '
    'dt.min_exec_time, '
    'dt.max_exec_time, '
    'dt.mean_exec_time, '
    'dt.stddev_exec_time, '
    'dt.rows, '
    'dt.shared_blks_hit, '
    'dt.shared_blks_read, '
    'dt.shared_blks_dirtied, '
    'dt.shared_blks_written, '
    'dt.local_blks_hit, '
    'dt.local_blks_read, '
    'dt.local_blks_dirtied, '
    'dt.local_blks_written, '
    'dt.temp_blks_read, '
    'dt.temp_blks_written, '
    'dt.blk_read_time, '
    'dt.blk_write_time, '
    'dt.wal_records, '
    'dt.wal_fpi, '
    'dt.wal_bytes '
  'FROM %1$s imp '
    'CROSS JOIN json_to_record(imp.row_data) AS '
      'dt ( '
        'server_id            integer, '
        'sample_id            integer, '
        'userid               oid, '
        'datid                oid, '
        'queryid              bigint, '
        'queryid_md5          character(32), '
        'plans                bigint, '
        'total_plan_time      double precision, '
        'min_plan_time        double precision, '
        'max_plan_time        double precision, '
        'mean_plan_time       double precision, '
        'stddev_plan_time     double precision, '
        'calls                bigint, '
        'total_exec_time      double precision, '
        'min_exec_time        double precision, '
        'max_exec_time        double precision, '
        'mean_exec_time       double precision, '
        'stddev_exec_time     double precision, '
        'rows                 bigint, '
        'shared_blks_hit      bigint, '
        'shared_blks_read     bigint, '
        'shared_blks_dirtied  bigint, '
        'shared_blks_written  bigint, '
        'local_blks_hit       bigint, '
        'local_blks_read      bigint, '
        'local_blks_dirtied   bigint, '
        'local_blks_written   bigint, '
        'temp_blks_read       bigint, '
        'temp_blks_written    bigint, '
        'blk_read_time        double precision, '
        'blk_write_time       double precision, '
        'wal_records          bigint, '
        'wal_fpi              bigint, '
        'wal_bytes            numeric '
      ') '
    'JOIN jsonb_to_recordset($1) AS '
      'srv_map ( '
        'imp_srv_id    integer, '
        'local_srv_id  integer '
      ') ON '
      '(srv_map.imp_srv_id = dt.server_id) '
    'LEFT OUTER JOIN sample_statements ld ON '
      '(ld.server_id = srv_map.local_srv_id AND ld.sample_id = dt.sample_id AND ld.datid = dt.datid '
      'AND ld.userid = dt.userid AND ld.queryid = dt.queryid) '
  'WHERE ld.server_id IS NULL AND imp.section_id = $2 '
),
('pg_profile','0.3.2', 1,'sample_kcache',
  'INSERT INTO sample_kcache (server_id,sample_id,userid,datid,queryid,'
    'queryid_md5,plan_user_time,plan_system_time,plan_minflts,plan_majflts,'
    'plan_nswaps,plan_reads,plan_writes,plan_msgsnds,plan_msgrcvs,plan_nsignals,'
    'plan_nvcsws,plan_nivcsws,exec_user_time,exec_system_time,exec_minflts,'
    'exec_majflts,exec_nswaps,exec_reads,exec_writes,exec_msgsnds,exec_msgrcvs,'
    'exec_nsignals,exec_nvcsws,exec_nivcsws)'
  'SELECT '
    'srv_map.local_srv_id, '
    'dt.sample_id, '
    'dt.userid, '
    'dt.datid, '
    'dt.queryid, '
    'dt.queryid_md5, '
    'dt.plan_user_time, '
    'dt.plan_system_time, '
    'dt.plan_minflts, '
    'dt.plan_majflts, '
    'dt.plan_nswaps, '
    'dt.plan_reads, '
    'dt.plan_writes, '
    'dt.plan_msgsnds, '
    'dt.plan_msgrcvs, '
    'dt.plan_nsignals, '
    'dt.plan_nvcsws, '
    'dt.plan_nivcsws, '
    'dt.exec_user_time, '
    'dt.exec_system_time, '
    'dt.exec_minflts, '
    'dt.exec_majflts, '
    'dt.exec_nswaps, '
    'dt.exec_reads, '
    'dt.exec_writes, '
    'dt.exec_msgsnds, '
    'dt.exec_msgrcvs, '
    'dt.exec_nsignals, '
    'dt.exec_nvcsws, '
    'dt.exec_nivcsws '
  'FROM %1$s imp '
    'CROSS JOIN json_to_record(imp.row_data) AS '
      'dt ( '
        'server_id         integer, '
        'sample_id         integer, '
        'userid            oid, '
        'datid             oid, '
        'queryid           bigint, '
        'queryid_md5       character(32), '
        'plan_user_time    double precision, '
        'plan_system_time  double precision, '
        'plan_minflts      bigint, '
        'plan_majflts      bigint, '
        'plan_nswaps       bigint, '
        'plan_reads        bigint, '
        'plan_writes       bigint, '
        'plan_msgsnds      bigint, '
        'plan_msgrcvs      bigint, '
        'plan_nsignals     bigint, '
        'plan_nvcsws       bigint, '
        'plan_nivcsws      bigint, '
        'exec_user_time    double precision, '
        'exec_system_time  double precision, '
        'exec_minflts      bigint, '
        'exec_majflts      bigint, '
        'exec_nswaps       bigint, '
        'exec_reads        bigint, '
        'exec_writes       bigint, '
        'exec_msgsnds      bigint, '
        'exec_msgrcvs      bigint, '
        'exec_nsignals     bigint, '
        'exec_nvcsws       bigint, '
        'exec_nivcsws      bigint '
      ') '
    'JOIN jsonb_to_recordset($1) AS '
      'srv_map ( '
        'imp_srv_id    integer, '
        'local_srv_id  integer '
      ') ON '
      '(srv_map.imp_srv_id = dt.server_id) '
    'LEFT OUTER JOIN sample_kcache ld ON '
      '(ld.server_id = srv_map.local_srv_id AND ld.sample_id = dt.sample_id AND ld.datid = dt.datid '
      'AND ld.userid = dt.userid AND ld.queryid = dt.queryid) '
  'WHERE ld.server_id IS NULL AND imp.section_id = $2 '
);

 /*
  * Support import from pg_profile 0.3.1
  */
INSERT INTO import_queries VALUES
-- queryid_md5 mapping temporary table
('pg_profile','0.3.1', 1,'stmt_list',
  'CREATE TEMPORARY TABLE queryid_map('
    'server_id,'
    'queryid_md5_old,'
    'queryid_md5_new'
  ') '
  'ON COMMIT DROP '
  'AS SELECT DISTINCT '
    'srv_map.local_srv_id, '
    'dt.queryid_md5, '
    'md5(dt.query) '
  'FROM %1$s imp '
    'CROSS JOIN json_to_record(imp.row_data) AS '
      'dt ( '
        'server_id    integer, '
        'queryid_md5  character(10), '
        'query        text '
      ') '
    'JOIN jsonb_to_recordset($1) AS '
      'srv_map ( '
        'imp_srv_id    integer, '
        'local_srv_id  integer '
      ') ON '
      '(srv_map.imp_srv_id = dt.server_id) '
    'LEFT OUTER JOIN stmt_list ld ON '
      '(ld.server_id = srv_map.local_srv_id AND ld.queryid_md5 = md5(dt.query)) '
  'WHERE ld.server_id IS NULL AND imp.section_id = $2 '
),
-- Actual statements list load
('pg_profile','0.3.1', 2,'stmt_list',
  'INSERT INTO stmt_list (server_id,queryid_md5,query)'
  'SELECT DISTINCT '
    'srv_map.local_srv_id, '
    'md5(dt.query), '
    'dt.query '
  'FROM %1$s imp '
    'CROSS JOIN json_to_record(imp.row_data) AS '
      'dt ( '
        'server_id    integer, '
        'query        text '
      ') '
    'JOIN jsonb_to_recordset($1) AS '
      'srv_map ( '
        'imp_srv_id    integer, '
        'local_srv_id  integer '
      ') ON '
      '(srv_map.imp_srv_id = dt.server_id) '
    'LEFT OUTER JOIN stmt_list ld ON '
      '(ld.server_id = srv_map.local_srv_id AND ld.queryid_md5 = md5(dt.query)) '
  'WHERE ld.server_id IS NULL AND imp.section_id = $2 '
),
('pg_profile','0.3.1', 1,'sample_statements',
  'INSERT INTO sample_statements (server_id,sample_id,userid,datid,queryid,queryid_md5,'
    'plans,total_plan_time,min_plan_time,max_plan_time,mean_plan_time,stddev_plan_time,'
    'calls,total_exec_time,min_exec_time,max_exec_time,mean_exec_time,stddev_exec_time,'
    'rows,shared_blks_hit,shared_blks_read,shared_blks_dirtied,shared_blks_written,'
    'local_blks_hit,local_blks_read,local_blks_dirtied,local_blks_written,'
    'temp_blks_read,temp_blks_written,blk_read_time,blk_write_time,wal_records,'
    'wal_fpi,wal_bytes)'
  'SELECT '
    'srv_map.local_srv_id, '
    'dt.sample_id, '
    'dt.userid, '
    'dt.datid, '
    'dt.queryid, '
    'q_map.queryid_md5_new, '
    'dt.plans, '
    'dt.total_plan_time, '
    'dt.min_plan_time, '
    'dt.max_plan_time, '
    'dt.mean_plan_time, '
    'dt.stddev_plan_time, '
    'dt.calls, '
    'dt.total_exec_time, '
    'dt.min_exec_time, '
    'dt.max_exec_time, '
    'dt.mean_exec_time, '
    'dt.stddev_exec_time, '
    'dt.rows, '
    'dt.shared_blks_hit, '
    'dt.shared_blks_read, '
    'dt.shared_blks_dirtied, '
    'dt.shared_blks_written, '
    'dt.local_blks_hit, '
    'dt.local_blks_read, '
    'dt.local_blks_dirtied, '
    'dt.local_blks_written, '
    'dt.temp_blks_read, '
    'dt.temp_blks_written, '
    'dt.blk_read_time, '
    'dt.blk_write_time, '
    'dt.wal_records, '
    'dt.wal_fpi, '
    'dt.wal_bytes '
  'FROM %1$s imp '
    'CROSS JOIN json_to_record(imp.row_data) AS '
      'dt ( '
        'server_id            integer, '
        'sample_id            integer, '
        'userid               oid, '
        'datid                oid, '
        'queryid              bigint, '
        'queryid_md5          character(10), '
        'plans                bigint, '
        'total_plan_time      double precision, '
        'min_plan_time        double precision, '
        'max_plan_time        double precision, '
        'mean_plan_time       double precision, '
        'stddev_plan_time     double precision, '
        'calls                bigint, '
        'total_exec_time      double precision, '
        'min_exec_time        double precision, '
        'max_exec_time        double precision, '
        'mean_exec_time       double precision, '
        'stddev_exec_time     double precision, '
        'rows                 bigint, '
        'shared_blks_hit      bigint, '
        'shared_blks_read     bigint, '
        'shared_blks_dirtied  bigint, '
        'shared_blks_written  bigint, '
        'local_blks_hit       bigint, '
        'local_blks_read      bigint, '
        'local_blks_dirtied   bigint, '
        'local_blks_written   bigint, '
        'temp_blks_read       bigint, '
        'temp_blks_written    bigint, '
        'blk_read_time        double precision, '
        'blk_write_time       double precision, '
        'wal_records          bigint, '
        'wal_fpi              bigint, '
        'wal_bytes            numeric '
      ') '
    'JOIN jsonb_to_recordset($1) AS '
      'srv_map ( '
        'imp_srv_id    integer, '
        'local_srv_id  integer '
      ') ON '
      '(srv_map.imp_srv_id = dt.server_id) '
    'JOIN queryid_map q_map ON (srv_map.local_srv_id, dt.queryid_md5) = (q_map.server_id, q_map.queryid_md5_old) '
    'LEFT OUTER JOIN sample_statements ld ON '
      '(ld.server_id = srv_map.local_srv_id AND ld.sample_id = dt.sample_id AND ld.datid = dt.datid '
      'AND ld.userid = dt.userid AND ld.queryid = dt.queryid) '
  'WHERE ld.server_id IS NULL AND imp.section_id = $2 '
),
('pg_profile','0.3.1', 1,'sample_kcache',
  'INSERT INTO sample_kcache (server_id,sample_id,userid,datid,queryid,'
    'queryid_md5,plan_user_time,plan_system_time,plan_minflts,plan_majflts,'
    'plan_nswaps,plan_reads,plan_writes,plan_msgsnds,plan_msgrcvs,plan_nsignals,'
    'plan_nvcsws,plan_nivcsws,exec_user_time,exec_system_time,exec_minflts,'
    'exec_majflts,exec_nswaps,exec_reads,exec_writes,exec_msgsnds,exec_msgrcvs,'
    'exec_nsignals,exec_nvcsws,exec_nivcsws)'
  'SELECT '
    'srv_map.local_srv_id, '
    'dt.sample_id, '
    'dt.userid, '
    'dt.datid, '
    'dt.queryid, '
    'q_map.queryid_md5_new, '
    'dt.plan_user_time, '
    'dt.plan_system_time, '
    'dt.plan_minflts, '
    'dt.plan_majflts, '
    'dt.plan_nswaps, '
    'dt.plan_reads, '
    'dt.plan_writes, '
    'dt.plan_msgsnds, '
    'dt.plan_msgrcvs, '
    'dt.plan_nsignals, '
    'dt.plan_nvcsws, '
    'dt.plan_nivcsws, '
    'dt.exec_user_time, '
    'dt.exec_system_time, '
    'dt.exec_minflts, '
    'dt.exec_majflts, '
    'dt.exec_nswaps, '
    'dt.exec_reads, '
    'dt.exec_writes, '
    'dt.exec_msgsnds, '
    'dt.exec_msgrcvs, '
    'dt.exec_nsignals, '
    'dt.exec_nvcsws, '
    'dt.exec_nivcsws '
  'FROM %1$s imp '
    'CROSS JOIN json_to_record(imp.row_data) AS '
      'dt ( '
        'server_id         integer, '
        'sample_id         integer, '
        'userid            oid, '
        'datid             oid, '
        'queryid           bigint, '
        'queryid_md5       character(10), '
        'plan_user_time    double precision, '
        'plan_system_time  double precision, '
        'plan_minflts      bigint, '
        'plan_majflts      bigint, '
        'plan_nswaps       bigint, '
        'plan_reads        bigint, '
        'plan_writes       bigint, '
        'plan_msgsnds      bigint, '
        'plan_msgrcvs      bigint, '
        'plan_nsignals     bigint, '
        'plan_nvcsws       bigint, '
        'plan_nivcsws      bigint, '
        'exec_user_time    double precision, '
        'exec_system_time  double precision, '
        'exec_minflts      bigint, '
        'exec_majflts      bigint, '
        'exec_nswaps       bigint, '
        'exec_reads        bigint, '
        'exec_writes       bigint, '
        'exec_msgsnds      bigint, '
        'exec_msgrcvs      bigint, '
        'exec_nsignals     bigint, '
        'exec_nvcsws       bigint, '
        'exec_nivcsws      bigint '
      ') '
    'JOIN jsonb_to_recordset($1) AS '
      'srv_map ( '
        'imp_srv_id    integer, '
        'local_srv_id  integer '
      ') ON '
      '(srv_map.imp_srv_id = dt.server_id) '
    'JOIN queryid_map q_map ON (srv_map.local_srv_id, dt.queryid_md5) = (q_map.server_id, q_map.queryid_md5_old) '
    'LEFT OUTER JOIN sample_kcache ld ON '
      '(ld.server_id = srv_map.local_srv_id AND ld.sample_id = dt.sample_id AND ld.datid = dt.datid '
      'AND ld.userid = dt.userid AND ld.queryid = dt.queryid) '
  'WHERE ld.server_id IS NULL AND imp.section_id = $2 '
)
;
