{
 "title": "pg_profile wait statistics",
 "tags": [ "pg_profile" ],
 "templating": {
  "list": [
   {
    "name": "ProfileDB",
    "label": "Database with pg_profile extension",
    "query": "postgres"
   },
   {
    "name": "profile_servers",
    "label": "Server",
    "query": "select server_id as __value, server_name as __text FROM servers"
   },
   {
    "name": "startid",
    "label": "StartID",
    "query": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__from:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__from:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
   },
   {
    "name": "endid",
    "label": "EndID",
    "query": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__to:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__to:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
   },
   {
    "name": "min_from",
    "query": "SELECT extract(epoch from min(sample_time))*1000 + 1 as min_from\nFROM samples\nWHERE\n  server_id = $profile_servers"
   },
   {
    "name": "max_to",
    "query": "SELECT extract(epoch from max(sample_time))*1000 + 1 as max_to\nFROM samples\nWHERE\n  server_id = $profile_servers"
   },
   {
    "name": "we_types",
    "query": "SELECT\n  event_type AS __value\nFROM\n  wait_sampling_total\nWHERE\n  server_id = $profile_servers\n  AND sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY event_type\nORDER BY sum(tot_waited) DESC;"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Report generation",
   "type": "text",
   "description": "Use provided pg_profile function call to get report of observable interval",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "get_report(${profile_servers},${startid},${endid})\n"
   },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__from:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__from:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
    },
    {
     "rawSql": "SELECT sample_id as EndID\nFROM samples\nWHERE\n  server_id = $profile_servers AND\n  sample_time < '${__to:date:iso}'\nORDER BY sample_id DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  reset_val\nFROM settings_and_changes($profile_servers, $startid, $endid)\nWHERE name = 'version'\nORDER BY first_seen ASC"
    }
   ]
  },
  { "title": "Cluster statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Overall statement times",
   "type": "stat",
   "description": "Summary pg_stat_statements  extension data",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (coalesce(sum(total_plan_time), 0) + sum(total_exec_time)) / 1000 as \"Elapsed (s)\",\n  (sum(shared_blk_read_time) + sum(shared_blk_write_time)) / 1000 as \"I/O time (s)\"\nFROM sample_statements_total sst\nWHERE\n  sst.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Overall wait times",
   "type": "stat",
   "description": "Overall time waited. Summary of pg_wait_sampling data.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(tot_waited)/1000 as \"Total Waited (s)\",\n  sum(stmt_waited)/1000 as \"Statements Waited (s)\"\nFROM wait_sampling_total wst\nWHERE\n  wst.server_id = ${profile_servers}\n  AND wst.sample_id BETWEEN $startid + 1 AND $endid\n"
    }
   ]
  },
  { "title": "Wait statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Statements wait event types",
   "type": "timeseries",
   "description": "Time waited in each wait event type per second from pg_wait_sampling extension (for statement waits)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wst.event_type as wet,\n  sum(stmt_waited / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Waited\"\nFROM wait_sampling_total wst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  wst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, wst.event_type\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total wait event types",
   "type": "timeseries",
   "description": "Time waited in each wait event type per second from pg_wait_sampling extension (for all waits)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wst.event_type as wet,\n  sum(tot_waited / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Waited\"\nFROM wait_sampling_total wst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  wst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, wst.event_type\nORDER BY time"
    }
   ]
  },
  {
   "title": "Statements wait events ($we_types)",
   "type": "timeseries",
   "description": "Time waited in each wait event per second from pg_wait_sampling extension (for statements $we_types waits)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "repeat": "we_types",
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wst.event as we,\n  sum(stmt_waited / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Waited\"\nFROM wait_sampling_total wst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  wst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\n  AND wst.event_type = ${we_types:singlequote}\nGROUP BY time, wst.event\nORDER BY time"
    }
   ]
  },
  {
   "title": "Total wait events ($we_types)",
   "type": "timeseries",
   "description": "Time waited in each wait event type per second from pg_wait_sampling extension (for $we_types waits)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "repeat": "we_types",
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wst.event as we,\n  sum(tot_waited / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Waited\"\nFROM wait_sampling_total wst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  wst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\n  AND wst.event_type = ${we_types:singlequote}\nGROUP BY time, wst.event\nORDER BY time"
    }
   ]
  }
 ]
}