{
 "title": "pg_profile vacuum",
 "description": "Vacuum statistics",
 "tags": [ "pg_profile" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ProfileDB",
    "label": "Database with pg_profile extension",
    "query": "postgres"
   },
   {
    "name": "profile_servers",
    "label": "Server",
    "query": "select server_id as __value, server_name as __text FROM servers"
   },
   {
    "name": "startid",
    "label": "StartID",
    "query": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__from:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__from:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
   },
   {
    "name": "endid",
    "label": "EndID",
    "query": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__to:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__to:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
   },
   {
    "name": "min_from",
    "query": "SELECT extract(epoch from min(sample_time))*1000 + 1 as min_from\nFROM samples\nWHERE\n  server_id = $profile_servers"
   },
   {
    "name": "max_to",
    "query": "SELECT extract(epoch from max(sample_time))*1000 + 1 as max_to\nFROM samples\nWHERE\n  server_id = $profile_servers"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Report generation",
   "type": "text",
   "description": "Use provided pg_profile function call to get report of observable interval",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "get_report(${profile_servers},${startid},${endid})\n"
   },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__from:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__from:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
    },
    {
     "rawSql": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__to:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__to:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  reset_val\nFROM settings_and_changes($profile_servers, $startid, $endid)\nWHERE name = 'version'\nORDER BY first_seen ASC"
    }
   ]
  },
  { "title": "Cluster stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "WAL",
   "type": "stat",
   "description": "LSN and pg_stat_archiver increment",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(wal_size) as \"Bytes\",\n  sum(archived_count) as \"Archived\",\n  sum(failed_count) as \"Archive failed\"\nFROM sample_stat_cluster sc JOIN sample_stat_archiver sa USING (server_id, sample_id)\nWHERE\n  sc.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "description": "Summary transaction data from pg_stat_database view",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(xact_commit) as \"Commit\",\n  sum(xact_rollback) as \"Rollback\",\n  sum(deadlocks) as \"Deadlocks\"\nFROM sample_stat_database sc\nWHERE\n  sc.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Commit rate data from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "si:tps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(xact_rollback) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Rollbacks\",\n  sum(xact_commit) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Commits\"\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Commit rate data from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(wal_bytes) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Statements WAL\"\nFROM sample_statements_total sst \n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND $__timeFilter(smpe.sample_time)\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wal_size / extract(epoch from smpe.sample_time - smps.sample_time) as \"Cluster WAL\"\nFROM sample_stat_cluster sc \n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sc.server_id = ${profile_servers}\n  AND $__timeFilter(smpe.sample_time)\nORDER BY time\n"
    }
   ]
  },
  { "title": "Vacuum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Vacuum runs per minute",
   "type": "timeseries",
   "description": "Cluster vacuum runs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(vacuum_count) / extract(epoch from smpe.sample_time - smps.sample_time) / 60 as \"Vacuum\",\n  sum(autovacuum_count) / extract(epoch from smpe.sample_time - smps.sample_time) / 60 as \"Autovacuum\"\nFROM sample_stat_tables_total st JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  st.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Analyze runs per minute",
   "type": "timeseries",
   "description": "Cluster vacuum runs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(analyze_count) / extract(epoch from smpe.sample_time - smps.sample_time) / 60 as \"Analyze\",\n  sum(autoanalyze_count) / extract(epoch from smpe.sample_time - smps.sample_time) / 60 as \"Autoanalyze\"\nFROM sample_stat_tables_total st JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  st.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Vacuum time spent (in seconds per second)",
   "type": "timeseries",
   "description": "Cluster vacuum time spent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(total_vacuum_time) / extract(epoch from smpe.sample_time - smps.sample_time) / 1000 as \"Vacuum time\",\n  sum(total_autovacuum_time) / extract(epoch from smpe.sample_time - smps.sample_time) / 1000 as \"Autovacuum time\"\nFROM sample_stat_tables_total st JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  st.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Analyze time spent (in seconds per second)",
   "type": "timeseries",
   "description": "Cluster vacuum time spent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(total_analyze_time) / extract(epoch from smpe.sample_time - smps.sample_time) / 1000 as \"Analyze time\",\n  sum(total_autoanalyze_time) / extract(epoch from smpe.sample_time - smps.sample_time) / 1000 as \"Autoanalyze time\"\nFROM sample_stat_tables_total st JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  st.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  }
 ]
}