{
 "title": "pg_profile summary",
 "tags": [ "pg_profile" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ProfileDB",
    "label": "Database with pg_profile extension",
    "query": "postgres"
   },
   {
    "name": "profile_servers",
    "label": "Server",
    "query": "select server_id as __value, server_name as __text FROM servers"
   },
   {
    "name": "startid",
    "label": "StartID",
    "query": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__from:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__from:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
   },
   {
    "name": "endid",
    "label": "EndID",
    "query": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__to:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__to:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
   },
   {
    "name": "min_from",
    "query": "SELECT extract(epoch from min(sample_time))*1000 + 1 as min_from\nFROM samples\nWHERE\n  server_id = $profile_servers"
   },
   {
    "name": "max_to",
    "query": "SELECT extract(epoch from max(sample_time))*1000 + 1 as max_to\nFROM samples\nWHERE\n  server_id = $profile_servers"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Report generation",
   "type": "text",
   "description": "Use provided pg_profile function call to get report of observable interval",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "get_report(${profile_servers},${startid},${endid})\n"
   }
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  reset_val\nFROM settings_and_changes($profile_servers, $startid, $endid)\nWHERE name = 'version'\nORDER BY first_seen ASC"
    }
   ]
  },
  { "title": "Cluster stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "WAL",
   "type": "stat",
   "description": "LSN and pg_stat_archiver increment",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(wal_size) as \"Bytes\",\n  sum(archived_count) as \"Archived\",\n  sum(failed_count) as \"Archive failed\"\nFROM sample_stat_cluster sc JOIN sample_stat_archiver sa USING (server_id, sample_id)\nWHERE\n  sc.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "description": "Summary transaction data from pg_stat_database view",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(xact_commit) as \"Commit\",\n  sum(xact_rollback) as \"Rollback\",\n  sum(deadlocks) as \"Deadlocks\"\nFROM sample_stat_database sc\nWHERE\n  sc.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Overall Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(blks_hit) * 100 / nullif(sum(blks_hit) + sum(blks_read), 0)\nFROM sample_stat_database sd\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND sample_id BETWEEN $startid  + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Temporary files",
   "type": "stat",
   "description": "Summary transaction data from pg_stat_database view",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(temp_files) as \"Files\",\n  sum(temp_bytes) as \"Size\"\nFROM sample_stat_database sc\nWHERE\n  sc.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid "
    }
   ]
  },
  {
   "title": "Overall statement times",
   "type": "stat",
   "description": "Summary pg_stat_statements  extension data",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (coalesce(sum(total_plan_time), 0) + sum(total_exec_time)) / 1000 as \"Elapsed (s)\",\n  (sum(shared_blk_read_time) + sum(shared_blk_write_time)) / 1000 as \"I/O time (s)\"\nFROM sample_statements_total sst\nWHERE\n  sst.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Tps",
   "type": "stat",
   "description": "Transactions per second",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (sum(xact_commit) + sum(xact_rollback)) /(SELECT EXTRACT( EPOCH FROM (select sample_time from samples where sample_id = $endid and server_id = $profile_servers ) - (select sample_time from samples where sample_id = $startid and server_id = $profile_servers))) as \"tps\"\nFROM sample_stat_database sc\nWHERE\n  sc.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid "
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Commit rate data from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "si:tps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(xact_rollback) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Rollbacks\",\n  sum(xact_commit) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Commits\"\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Transactions by database",
   "type": "timeseries",
   "description": "Commit rate data from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "si:tps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(xact_rollback + xact_commit) / extract(epoch from smpe.sample_time - smps.sample_time) as \":\",\n  sd.datname\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time, sd.datname\nORDER BY time"
    }
   ]
  },
  {
   "title": "Cluster commits",
   "type": "timeseries",
   "description": "Commit rate data from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "si:tps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(xact_commit) / extract(epoch from smpe.sample_time - smps.sample_time) as commits_ps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Cluster rollbacks",
   "type": "timeseries",
   "description": "Rollback rate data from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(xact_rollback) / extract(epoch from smpe.sample_time - smps.sample_time) as rollback_ps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "description": "Cluster session statistics from pg_stat_database. Available since Postgres 14",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(sessions) / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as sessions,\n  sum(sessions_abandoned) / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as sessions_abandoned,\n  sum(sessions_fatal) / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as sessions_fatal,\n  sum(sessions_killed) / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as sessions_killed\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Session times",
   "type": "timeseries",
   "description": "Cluster session timing statistics from pg_stat_database. Available since Postgres 14",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(session_time) / 1000 / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as session_time,\n  sum(active_time) / 1000  / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as active_time,\n  sum(idle_in_transaction_time) / 1000  / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as idle_in_transaction_time\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Parallel workers per second",
   "type": "timeseries",
   "description": "Parallel workers from pg_stat_database view. Available since Postgres 18",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(parallel_workers_to_launch) / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as \"Planned\",\n  sum(parallel_workers_launched) / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as \"Launched\"\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time\nORDER BY time\n"
    }
   ]
  },
  { "title": "Database sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Cluster size",
   "type": "timeseries",
   "description": "Sum of cluster database sizes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(sd.datsize)\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND sd.sample_id BETWEEN $startid + 1 AND $endid \nGROUP BY smpe.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Cluster size by database",
   "type": "timeseries",
   "description": "Sum of cluster database sizes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  sum(sd.datsize) as \":\"\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND sd.sample_id BETWEEN $startid + 1 AND $endid \nGROUP BY smpe.sample_time, sd.datname\nORDER BY time"
    }
   ]
  },
  { "title": "Vacuum stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Top databases by dead tuples",
   "type": "timeseries",
   "description": "Number of dead tuples by databases",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH last_stat AS (\n  SELECT \n    datid, \n    sum(n_dead_tup) AS sum_dead_tup \n  FROM sample_stat_tables \n  WHERE sample_id BETWEEN $startid + 1 AND $endid\n  GROUP BY datid\n  ORDER BY sum_dead_tup DESC\n  LIMIT 20\n)\nSELECT \n  smpe.sample_time AS time,\n  db.datname AS database, \n  sum(st.n_dead_tup) AS \":\"\nFROM sample_stat_tables AS st \nJOIN samples smpe USING (server_id, sample_id)\nJOIN pg_database AS db ON db.oid = st.datid\nJOIN last_stat AS ls ON ls.datid = st.datid\nGROUP BY database, time\nORDER BY smpe.sample_time;"
    }
   ]
  },
  {
   "title": "Dead tuples by database",
   "type": "piechart",
   "description": "Top 20 databases by sum of dead tuples generated in period",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  db.datname AS database, \n  sum(st.n_dead_tup) AS sum_dead_tup\nFROM sample_stat_tables AS st \nJOIN samples smpe USING (server_id, sample_id)\nJOIN pg_database AS db ON db.oid = st.datid\nWHERE sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY database\nORDER BY sum_dead_tup DESC\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Top tables by dead tuples",
   "type": "timeseries",
   "description": "Number of dead tuples by tables",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH last_stat AS (\n  SELECT \n    relid,\n    sum(n_dead_tup) AS sum_dead_tup \n  FROM sample_stat_tables \n  WHERE sample_id BETWEEN $startid + 1 AND $endid\n  GROUP BY relid\n  ORDER BY sum_dead_tup DESC\n  LIMIT 20\n)\nSELECT \n  smpe.sample_time AS time,\n  lst.relname,\n  sum(st.n_dead_tup) AS \":\"\nFROM sample_stat_tables AS st \nJOIN samples smpe USING (server_id, sample_id)\nJOIN last_stat AS ls ON ls.relid = st.relid\nJOIN last_stat_tables AS lst ON lst.relid = st.relid\nGROUP BY lst.relname, time\nORDER BY smpe.sample_time;"
    }
   ]
  },
  {
   "title": "Dead tuples by tables",
   "type": "piechart",
   "description": "Top 20 tables by sum of dead tuples generated in period",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  lst.relname AS relname, \n  sum(st.n_dead_tup) AS sum_dead_tup\nFROM sample_stat_tables AS st \nJOIN samples smpe USING (server_id, sample_id)\nJOIN last_stat_tables AS lst ON lst.relid = st.relid\nWHERE st.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY relname\nORDER BY sum_dead_tup DESC\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Vacuum runs per minute",
   "type": "timeseries",
   "description": "Cluster vacuum runs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(vacuum_count) / extract(epoch from smpe.sample_time - smps.sample_time) / 60 as \"Vacuum\",\n  sum(autovacuum_count) / extract(epoch from smpe.sample_time - smps.sample_time) / 60 as \"Autovacuum\"\nFROM sample_stat_tables_total st JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  st.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Analyze runs per minute",
   "type": "timeseries",
   "description": "Cluster vacuum runs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(analyze_count) / extract(epoch from smpe.sample_time - smps.sample_time) / 60 as \"Analyze\",\n  sum(autoanalyze_count) / extract(epoch from smpe.sample_time - smps.sample_time) / 60 as \"Autoanalyze\"\nFROM sample_stat_tables_total st JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  st.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  { "title": "Cluster I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Write",
   "type": "timeseries",
   "description": "Buffers write rate from pg_stat_bgwriter view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "si:blks/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  buffers_clean / extract(epoch from smpe.sample_time - smps.sample_time) as bgwriter,\n  buffers_checkpoint / extract(epoch from smpe.sample_time - smps.sample_time) as checkpointer,\n  buffers_backend / extract(epoch from smpe.sample_time - smps.sample_time) as backends\nFROM sample_stat_cluster sc JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sc.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY  time"
    }
   ]
  },
  {
   "title": "Cluster write time",
   "type": "timeseries",
   "description": "Time spent writing buffers from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "si:s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(blk_write_time) / 1000 / extract(epoch from smpe.sample_time - smps.sample_time) as write_sps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Cluster reads",
   "type": "timeseries",
   "description": "Read rate from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "si:blks/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(blks_read) / extract(epoch from smpe.sample_time - smps.sample_time) as read\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Cluster read time",
   "type": "timeseries",
   "description": "Time spent reading buffers from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "si:s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(blk_read_time) / 1000 / extract(epoch from smpe.sample_time - smps.sample_time) as read_sps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Cluster hits",
   "type": "timeseries",
   "description": "Buffer hits rate from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "si:blks/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(blks_hit) / extract(epoch from smpe.sample_time - smps.sample_time) as hit\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Hit ratio",
   "type": "timeseries",
   "description": "Hit ratio (calculated on pg_stat_database data)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(blks_hit) * 100 / \n  NULLIF(sum(blks_hit) + sum(blks_read), 0) as hit_pct\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time\nORDER BY time"
    }
   ]
  },
  { "title": "Write Ahead Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "WAL",
   "type": "timeseries",
   "description": "LSN increment and wal_bytes summary of pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wal_size / extract(epoch from smpe.sample_time - smps.sample_time) as \"Cluster WAL\"\nFROM sample_stat_cluster sc \n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sc.server_id = ${profile_servers}\n  AND $__timeFilter(smpe.sample_time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(wal_bytes) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Statements WAL\"\nFROM sample_statements_total sst \n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND $__timeFilter(smpe.sample_time)\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "WAL Archiving",
   "type": "timeseries",
   "description": "Based on pg_stat_archiver view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "segs/min" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  archived_count * 60 / extract(epoch from smpe.sample_time - smps.sample_time) as archived,\n  failed_count * 60 / extract(epoch from smpe.sample_time - smps.sample_time) as failed\nFROM sample_stat_archiver sa JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sa.server_id = ${profile_servers}\n  AND $__timeFilter(smpe.sample_time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "WAL records",
   "type": "timeseries",
   "description": "WAL records rate from pg_stat_wal view. Available since Postgres 14",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "si:r/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wal_records / extract(epoch from smpe.sample_time - smps.sample_time) as wrps\nFROM sample_stat_wal sw JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sw.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "WAL full page images",
   "type": "timeseries",
   "description": "WAL FPI rate from pg_stat_wal view. Available since Postgres 14",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": " fpi/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wal_fpi / extract(epoch from smpe.sample_time - smps.sample_time) as fpips\nFROM sample_stat_wal sw JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sw.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "WAL write and sync",
   "type": "timeseries",
   "description": "WAL write and sync rate from pg_stat_wal view. Available since Postgres 14",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  coalesce(statio_wal.wal_write, sw.wal_write) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Writes per second\",\n  coalesce(statio_wal.wal_sync, sw.wal_sync) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Syncs per second\"\nFROM sample_stat_wal sw JOIN samples smpe USING (server_id, sample_id)\n  JOIN (\n        SELECT\n          sample_id,\n          sum(writes)::bigint as wal_write,\n          sum(fsyncs)::bigint as wal_sync\n        FROM sample_stat_io io\n        WHERE server_id = ${profile_servers} AND sample_id BETWEEN $startid + 1 AND $endid\n          AND object = 'wal'\n        GROUP BY sample_id\n  ) statio_wal USING (sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sw.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "WAL write and sync time",
   "type": "timeseries",
   "description": "WAL write and sync time elapsed from pg_stat_wal view. Available since Postgres 14 if track_wal_io_timing setting is on.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  coalesce(statio_wal.wal_write_time, sw.wal_write_time) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Write time per second (s/s)\",\n  coalesce(statio_wal.wal_sync_time, sw.wal_sync_time) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Syncs time per second (s/s)\"\nFROM sample_stat_wal sw JOIN samples smpe USING (server_id, sample_id)\n  JOIN (\n        SELECT\n          sample_id,\n          sum(write_time)::bigint as wal_write_time,\n          sum(fsync_time)::bigint as wal_sync_time\n        FROM sample_stat_io io\n        WHERE server_id = ${profile_servers} AND sample_id BETWEEN $startid + 1 AND $endid\n          AND object = 'wal'\n        GROUP BY sample_id\n  ) statio_wal USING (sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sw.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  { "title": "Temp files by database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Temp files size",
   "type": "timeseries",
   "description": "Temporary size rate from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(temp_bytes) / extract(epoch from smpe.sample_time - smps.sample_time) as temp_bytes_ps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Cluster temp files generation rate",
   "type": "timeseries",
   "description": "Temporary files generation rate from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "files/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(temp_files) / extract(epoch from smpe.sample_time - smps.sample_time) as temp_files_ps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  { "title": "Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Statement time",
   "type": "timeseries",
   "description": "Times spent by statements on planning, execution, reading and writing from pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(total_plan_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Planning\",\n  sum(total_exec_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Execution\",\n  sum(sst.shared_blk_read_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Read\",\n  sum(sst.shared_blk_write_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Write\"\nFROM sample_statements_total sst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Statement plans/executions",
   "type": "timeseries",
   "description": "Planning and executions count from pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(calls / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Executions\",\n  sum(plans / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Plans\"\nFROM sample_statements_total sst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Statement temp I/O",
   "type": "timeseries",
   "description": "Temp blocks read and write rate from pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "si:blk/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(temp_blks_read / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Temp read\",\n  sum(temp_blks_written / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Temp written\"\nFROM sample_statements_total sst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Statement shared I/O",
   "type": "timeseries",
   "description": "Shared blocks read and write rate from pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "si:blk/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(shared_blks_read / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Shared read\",\n  sum(shared_blks_written / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Shared written\"\nFROM sample_statements_total sst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Statement local I/O",
   "type": "timeseries",
   "description": "Local blocks read and write rate from pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
   "fieldConfig": { "defaults": { "unit": "si:blk/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(local_blks_read / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Local read\",\n  sum(local_blks_written / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Local written\"\nFROM sample_statements_total sst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  { "title": "Wait sampling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 } },
  {
   "title": "Wait event types (statements)",
   "type": "timeseries",
   "description": "Time waited in each wait event type per second from pg_wait_sampling extension (for waits with queryid)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wst.event_type as wet,\n  sum(stmt_waited / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Waited\"\nFROM wait_sampling_total wst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  wst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, wst.event_type\nORDER BY time"
    }
   ]
  },
  {
   "title": "Wait event types (all)",
   "type": "timeseries",
   "description": "Time waited in each wait event type per second from pg_wait_sampling extension (for all waits)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wst.event_type as wet,\n  sum(tot_waited / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Waited\"\nFROM wait_sampling_total wst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  wst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, wst.event_type\nORDER BY time"
    }
   ]
  }
 ]
}