{
 "title": "pg_profile visualization",
 "time": { "from": "2022-03-31T12:54:44.001Z", "to": "2022-04-14T07:10:00.999Z" },
 "templating": {
  "list": [
   {
    "name": "ProfileDB",
    "label": "Database with pg_profile extension",
    "query": "postgres"
   },
   {
    "name": "profile_servers",
    "label": "Server",
    "query": "select server_id as __value, server_name as __text FROM servers"
   },
   {
    "name": "startid",
    "label": "StartID",
    "query": "SELECT sample_id as StartID\nFROM samples\nWHERE\n  server_id = $profile_servers AND\n  sample_time < '${__from:date:iso}'\nORDER BY sample_id DESC\nLIMIT 1"
   },
   {
    "name": "endid",
    "label": "EndID",
    "query": "SELECT sample_id as EndID\nFROM samples\nWHERE\n  server_id = $profile_servers AND\n  sample_time > '${__to:date:iso}'\nORDER BY sample_id ASC\nLIMIT 1"
   },
   {
    "name": "min_from",
    "query": "SELECT extract(epoch from min(sample_time))*1000 + 1 as min_from\nFROM samples\nWHERE\n  server_id = $profile_servers"
   },
   {
    "name": "max_to",
    "query": "SELECT extract(epoch from max(sample_time))*1000 - 1 as max_to\nFROM samples\nWHERE\n  server_id = $profile_servers"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Report generation",
   "type": "text",
   "description": "Use provided pg_profile function call to get report of observable interval",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "get_report(${profile_servers},${startid},${endid})\n"
   },
   "targets": [
    {
     "rawSql": "SELECT sample_id as StartID\nFROM samples\nWHERE\n  server_id = $profile_servers AND\n  sample_time < '${__from:date:iso}'\nORDER BY sample_id DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT sample_id as EndID\nFROM samples\nWHERE\n  server_id = $profile_servers AND\n  sample_time > '${__to:date:iso}'\nORDER BY sample_id ASC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  reset_val\nFROM settings_and_changes($profile_servers, $startid, $endid)\nWHERE name = 'version'\nORDER BY first_seen ASC"
    }
   ]
  },
  { "title": "Cluster stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "WAL",
   "type": "stat",
   "description": "LSN and pg_stat_archiver increment",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(wal_size) as \"Bytes\",\n  sum(archived_count) as \"Archived\",\n  sum(failed_count) as \"Archive failed\"\nFROM sample_stat_cluster sc JOIN sample_stat_archiver sa USING (server_id, sample_id)\nWHERE\n  sc.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Overall statement times",
   "type": "stat",
   "description": "Summary pg_stat_statements  extension data",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (coalesce(sum(total_plan_time), 0) + sum(total_exec_time)) / 1000 as \"Elapsed (s)\",\n  (sum(blk_read_time) + sum(blk_write_time)) / 1000 as \"I/O time (s)\"\nFROM sample_statements_total sst\nWHERE\n  sst.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Overall Hit Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(blks_hit) * 100 / nullif(sum(blks_hit) + sum(blks_read), 0)\nFROM sample_stat_database sd\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND sample_id BETWEEN $startid  + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Temporary files",
   "type": "stat",
   "description": "Summary transaction data from pg_stat_database view",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(temp_files) as \"Files\",\n  sum(temp_bytes) as \"Size\"\nFROM sample_stat_database sc\nWHERE\n  sc.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid "
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "description": "Summary transaction data from pg_stat_database view",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(xact_commit) as \"Commit\",\n  sum(xact_rollback) as \"Rollback\",\n  sum(deadlocks) as \"Deadlocks\"\nFROM sample_stat_database sc\nWHERE\n  sc.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "description": "Commit rate data from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "si:tps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(xact_rollback) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Rollbacks\",\n  sum(xact_commit) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Commits\"\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  { "title": "Database Sizes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Database sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  sd.datsize\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND sd.sample_id BETWEEN $startid + 1 AND $endid \nORDER BY time"
    }
   ]
  },
  {
   "title": "Cluster size",
   "type": "timeseries",
   "description": "Cluster size - summary databases size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(sd.datsize)\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND sd.sample_id BETWEEN $startid + 1 AND $endid \nGROUP BY smpe.sample_time\nORDER BY time"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Commits by database",
   "type": "timeseries",
   "description": "Commit rate data from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "si:tps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  xact_commit / extract(epoch from smpe.sample_time - smps.sample_time) as buffers_clean\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Rollbacks by database",
   "type": "timeseries",
   "description": "Rollback rate data from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "tps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  xact_rollback / extract(epoch from smpe.sample_time - smps.sample_time) as rollback\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "description": "Cluster session statistics from pg_stat_database. Available since Postgres 14",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(sessions) / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as sessions,\n  sum(sessions_abandoned) / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as sessions_abandoned,\n  sum(sessions_fatal) / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as sessions_fatal,\n  sum(sessions_killed) / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as sessions_killed\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "Session times",
   "type": "timeseries",
   "description": "Cluster session timing statistics from pg_stat_database. Available since Postgres 14",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(session_time) / 1000 / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as session_time,\n  sum(active_time) / 1000  / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as active_time,\n  sum(idle_in_transaction_time) / 1000  / extract(epoch from min(smpe.sample_time) - min(smps.sample_time)) as idle_in_transaction_time\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY smpe.sample_time\nORDER BY time\n"
    }
   ]
  },
  { "title": "Cluster I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Write",
   "type": "timeseries",
   "description": "Buffers write rate from pg_stat_bgwriter view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "si:blks/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  buffers_clean / extract(epoch from smpe.sample_time - smps.sample_time) as bgwriter,\n  buffers_checkpoint / extract(epoch from smpe.sample_time - smps.sample_time) as checkpointer,\n  buffers_backend / extract(epoch from smpe.sample_time - smps.sample_time) as backends\nFROM sample_stat_cluster sc JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sc.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY  time"
    }
   ]
  },
  {
   "title": "Write time by database",
   "type": "timeseries",
   "description": "Time spent writing buffers from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "si:s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  blk_write_time / 1000 / extract(epoch from smpe.sample_time - smps.sample_time) as write_sps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Reads by database",
   "type": "timeseries",
   "description": "Read rate from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "si:blks/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  blks_read / extract(epoch from smpe.sample_time - smps.sample_time) as read\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Read time by database",
   "type": "timeseries",
   "description": "Time spent reading buffers from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "si:s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  blk_read_time / 1000 / extract(epoch from smpe.sample_time - smps.sample_time) as read_sps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Hits by database",
   "type": "timeseries",
   "description": "Buffer hits rate from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "si:blks/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  blks_hit / extract(epoch from smpe.sample_time - smps.sample_time) as hit\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Hit ratio",
   "type": "timeseries",
   "description": "Hit ratio by database (calculated on pg_stat_database data)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  blks_hit * 100 / \n  NULLIF(blks_hit + blks_read, 0) as hit_pct\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  { "title": "Write Ahead Log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "WAL",
   "type": "timeseries",
   "description": "LSN increment and wal_bytes summary of pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wal_size / extract(epoch from smpe.sample_time - smps.sample_time) as \"Cluster WAL\"\nFROM sample_stat_cluster sc \n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sc.server_id = ${profile_servers}\n  AND $__timeFilter(smpe.sample_time)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(wal_bytes) / extract(epoch from smpe.sample_time - smps.sample_time) as \"Statements WAL\"\nFROM sample_statements_total sst \n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND $__timeFilter(smpe.sample_time)\nGROUP BY smpe.sample_time, smps.sample_time\nORDER BY time"
    }
   ]
  },
  {
   "title": "WAL Archiving",
   "type": "timeseries",
   "description": "Based on pg_stat_archiver view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "segs/min" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  archived_count * 60 / extract(epoch from smpe.sample_time - smps.sample_time) as archived,\n  failed_count * 60 / extract(epoch from smpe.sample_time - smps.sample_time) as failed\nFROM sample_stat_archiver sa JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sa.server_id = ${profile_servers}\n  AND $__timeFilter(smpe.sample_time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "WAL records",
   "type": "timeseries",
   "description": "WAL records rate from pg_stat_wal view. Available since Postgres 14",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "si:r/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wal_records / extract(epoch from smpe.sample_time - smps.sample_time) as wrps\nFROM sample_stat_wal sw JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sw.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "WAL full page images",
   "type": "timeseries",
   "description": "WAL FPI rate from pg_stat_wal view. Available since Postgres 14",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": " fpi/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wal_fpi / extract(epoch from smpe.sample_time - smps.sample_time) as fpips\nFROM sample_stat_wal sw JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sw.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "WAL write and sync",
   "type": "timeseries",
   "description": "WAL write and sync rate from pg_stat_wal view. Available since Postgres 14",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wal_write / extract(epoch from smpe.sample_time - smps.sample_time) as \"Writes per second\",\n  wal_sync / extract(epoch from smpe.sample_time - smps.sample_time) as \"Syncs per second\"\nFROM sample_stat_wal sw JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sw.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "WAL write and sync time",
   "type": "timeseries",
   "description": "WAL write and sync time elapsed from pg_stat_wal view. Available since Postgres 14 if track_wal_io_timing setting is on.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wal_write_time / extract(epoch from smpe.sample_time - smps.sample_time) as \"Write time per second (s/s)\",\n  wal_sync_time / extract(epoch from smpe.sample_time - smps.sample_time) as \"Syncs time per second (s/s)\"\nFROM sample_stat_wal sw JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sw.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  { "title": "Temp files by database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Temp files size",
   "type": "timeseries",
   "description": "Temporary size rate from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  temp_bytes / extract(epoch from smpe.sample_time - smps.sample_time) as temp_bytes_ps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Temp files generation",
   "type": "timeseries",
   "description": "Temporary files generation rate from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "files/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  temp_files / extract(epoch from smpe.sample_time - smps.sample_time) as temp_files_ps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  { "title": "Statements", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 } },
  {
   "title": "Statement time",
   "type": "timeseries",
   "description": "Times spent by statements on planning, execution, reading and writing from pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(total_plan_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Planning\",\n  sum(total_exec_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Execution\",\n  sum(sst.blk_read_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Read\",\n  sum(sst.blk_write_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Write\"\nFROM sample_statements_total sst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Statement plans/executions",
   "type": "timeseries",
   "description": "Planning and executions count from pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(calls / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Executions\",\n  sum(plans / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Plans\"\nFROM sample_statements_total sst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Statement temp I/O",
   "type": "timeseries",
   "description": "Temp blocks read and write rate from pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "si:blk/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(temp_blks_read / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Temp read\",\n  sum(temp_blks_written / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Temp written\"\nFROM sample_statements_total sst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Statement shared I/O",
   "type": "timeseries",
   "description": "Shared blocks read and write rate from pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "si:blk/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(shared_blks_read / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Shared read\",\n  sum(shared_blks_written / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Shared written\"\nFROM sample_statements_total sst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "Statement local I/O",
   "type": "timeseries",
   "description": "Local blocks read and write rate from pg_stat_statements",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "si:blk/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sum(local_blks_read / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Local read\",\n  sum(local_blks_written / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Local written\"\nFROM sample_statements_total sst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  { "title": "Wait sampling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 129 } },
  {
   "title": "Wait event types (statements)",
   "type": "timeseries",
   "description": "Time waited in each wait event type per second from pg_wait_sampling extension (for waits with queryid)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wst.event_type as wet,\n  sum(stmt_waited / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Waited\"\nFROM wait_sampling_total wst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  wst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, wst.event_type\nORDER BY time"
    }
   ]
  },
  {
   "title": "Wait event types (all)",
   "type": "timeseries",
   "description": "Time waited in each wait event type per second from pg_wait_sampling extension (for all waits)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  wst.event_type as wet,\n  sum(tot_waited / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Waited\"\nFROM wait_sampling_total wst\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  wst.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, wst.event_type\nORDER BY time"
    }
   ]
  }
 ]
}