{
 "title": "pg_profile IO statistics",
 "tags": [ "pg_profile" ],
 "templating": {
  "list": [
   {
    "name": "ProfileDB",
    "label": "Database with pg_profile extension",
    "query": "postgres"
   },
   {
    "name": "profile_servers",
    "label": "Server",
    "query": "select server_id as __value, server_name as __text FROM servers"
   },
   {
    "name": "startid",
    "label": "StartID",
    "query": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__from:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__from:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
   },
   {
    "name": "endid",
    "label": "EndID",
    "query": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__to:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__to:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
   },
   {
    "name": "min_from",
    "query": "SELECT extract(epoch from min(sample_time))*1000 + 1 as min_from\nFROM samples\nWHERE\n  server_id = $profile_servers"
   },
   {
    "name": "max_to",
    "query": "SELECT extract(epoch from max(sample_time))*1000 + 1 as max_to\nFROM samples\nWHERE\n  server_id = $profile_servers"
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Report generation",
   "type": "text",
   "description": "Use provided pg_profile function call to get report of observable interval",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "get_report(${profile_servers},${startid},${endid})\n"
   },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time < '${__from:date:iso}'\n  ORDER BY sample_id DESC\n  LIMIT 1),\n  (SELECT sample_id\n  FROM samples\n  WHERE\n    server_id = $profile_servers AND\n    sample_time > '${__from:date:iso}'\n  ORDER BY sample_id ASC\n  LIMIT 1)\n) as StartID"
    },
    {
     "rawSql": "SELECT sample_id as EndID\nFROM samples\nWHERE\n  server_id = $profile_servers AND\n  sample_time < '${__to:date:iso}'\nORDER BY sample_id DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  reset_val\nFROM settings_and_changes($profile_servers, $startid, $endid)\nWHERE name = 'version'\nORDER BY first_seen ASC"
    }
   ]
  },
  { "title": "Cluster statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Overall statement times",
   "type": "stat",
   "description": "Summary pg_stat_statements  extension data",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (coalesce(sum(total_plan_time), 0) + sum(total_exec_time)) / 1000 as \"Elapsed (s)\",\n  round(sum(shared_blk_read_time)::numeric / 1000, 2) as \"Read time (s)\",\n  round(sum(shared_blk_write_time)::numeric / 1000, 2) as \"Write time (s)\"\nFROM sample_statements_total sst\nWHERE\n  sst.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Cluster summary",
   "type": "stat",
   "description": "pg_stat_database summary",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  round(sum(blk_read_time)::numeric / 1000, 2) as \"Read time (s)\",\n  round(sum(blk_write_time)::numeric / 1000, 2) as \"Write time (s)\"\nFROM sample_stat_database sst\nWHERE\n  sst.server_id = ${profile_servers}\n  AND sample_id BETWEEN $startid + 1 AND $endid \n"
    }
   ]
  },
  {
   "title": "Cluster I/O (based on pg_stat_bgwriter and pg_stat_database)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Write",
   "type": "timeseries",
   "description": "Buffers write rate from pg_stat_bgwriter view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "si:blks/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  buffers_clean / extract(epoch from smpe.sample_time - smps.sample_time) as bgwriter,\n  buffers_checkpoint / extract(epoch from smpe.sample_time - smps.sample_time) as checkpointer,\n  buffers_backend / extract(epoch from smpe.sample_time - smps.sample_time) as backends\nFROM sample_stat_cluster sc JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sc.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY  time"
    }
   ]
  },
  {
   "title": "Write time by database",
   "type": "timeseries",
   "description": "Time spent writing buffers from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "si:s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  blk_write_time / 1000 / extract(epoch from smpe.sample_time - smps.sample_time) as write_sps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Reads by database",
   "type": "timeseries",
   "description": "Read rate from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "si:blks/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  blks_read / extract(epoch from smpe.sample_time - smps.sample_time) as read\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Read time by database",
   "type": "timeseries",
   "description": "Time spent reading buffers from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "si:s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  blk_read_time / 1000 / extract(epoch from smpe.sample_time - smps.sample_time) as read_sps\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Hits by database",
   "type": "timeseries",
   "description": "Buffer hits rate from pg_stat_database view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "si:blks/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  blks_hit / extract(epoch from smpe.sample_time - smps.sample_time) as hit\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Hit ratio",
   "type": "timeseries",
   "description": "Hit ratio by database (calculated on pg_stat_database data)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sd.datname as database,\n  blks_hit * 100 / \n  NULLIF(blks_hit + blks_read, 0) as hit_pct\nFROM sample_stat_database sd JOIN samples smpe USING (server_id, sample_id)\nWHERE\n  sd.server_id = ${profile_servers}\n  AND NOT datistemplate\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nORDER BY time"
    }
   ]
  },
  {
   "title": "Backends I/O (based on pg_stat_io)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 }
  },
  {
   "title": "Reads by backend types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.backend_type as bt,\n  sum(reads / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Reads\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, bt\nORDER BY time"
    }
   ]
  },
  {
   "title": "Read time by backend types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.backend_type as bt,\n  sum(read_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Read time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, bt\nORDER BY time"
    }
   ]
  },
  {
   "title": "Writes by backend types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.backend_type as bt,\n  sum(writes / extract(epoch from smpe.sample_time - smps.sample_time)) as \"writes\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, bt\nORDER BY time"
    }
   ]
  },
  {
   "title": "Write time by backend types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.backend_type as bt,\n  sum(write_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Read time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, bt\nORDER BY time"
    }
   ]
  },
  {
   "title": "Extends by backend types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "e/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.backend_type as bt,\n  sum(extends / extract(epoch from smpe.sample_time - smps.sample_time)) as \"extends\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, bt\nORDER BY time"
    }
   ]
  },
  {
   "title": "Extend time by backend types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.backend_type as bt,\n  sum(extend_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Read time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, bt\nORDER BY time"
    }
   ]
  },
  {
   "title": "Fsyncs by backend types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "fsyncs/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.backend_type as bt,\n  sum(coalesce(fsyncs, 0) / extract(epoch from smpe.sample_time - smps.sample_time)) as \"fsyncs per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, bt\nORDER BY time"
    }
   ]
  },
  {
   "title": "Fsync time by backend types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.backend_type as bt,\n  sum(fsync_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Fsync time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, bt\nORDER BY time"
    }
   ]
  },
  {
   "title": "Hits by backend types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "si:hits/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.backend_type as bt,\n  sum(coalesce(hits, 0) / extract(epoch from smpe.sample_time - smps.sample_time)) as \"extends\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, bt\nORDER BY time"
    }
   ]
  },
  {
   "title": "Reuses by backend types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "si:ru/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.backend_type as bt,\n  sum(coalesce(reuses, 0) / extract(epoch from smpe.sample_time - smps.sample_time)) as \"reuses per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, bt\nORDER BY time"
    }
   ]
  },
  {
   "title": "Contexts I/O (based on pg_stat_io)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 }
  },
  {
   "title": "Reads by context types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.context as ct,\n  sum(reads / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Reads\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ct\nORDER BY time"
    }
   ]
  },
  {
   "title": "Read time by context types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.context as ct,\n  sum(read_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Read time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ct\nORDER BY time"
    }
   ]
  },
  {
   "title": "Writes by context types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.context as ct,\n  sum(writes / extract(epoch from smpe.sample_time - smps.sample_time)) as \"writes\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ct\nORDER BY time"
    }
   ]
  },
  {
   "title": "Write time by context types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.context as ct,\n  sum(write_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Write time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ct\nORDER BY time"
    }
   ]
  },
  {
   "title": "Extends by context types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "e/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.context as ct,\n  sum(extends / extract(epoch from smpe.sample_time - smps.sample_time)) as \"extends\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ct\nORDER BY time"
    }
   ]
  },
  {
   "title": "Extend time by context types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.context as ct,\n  sum(extend_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Extend time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ct\nORDER BY time"
    }
   ]
  },
  {
   "title": "Fsyncs by context types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "fsyncs/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.context as ct,\n  sum(fsyncs / extract(epoch from smpe.sample_time - smps.sample_time)) as \"fsyncs\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ct\nORDER BY time"
    }
   ]
  },
  {
   "title": "Fsync time by context types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.context as ct,\n  sum(fsync_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Fsync time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ct\nORDER BY time"
    }
   ]
  },
  {
   "title": "Hits by context types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "si:hits/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.context as ct,\n  sum(hits / extract(epoch from smpe.sample_time - smps.sample_time)) as \"hits\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ct\nORDER BY time"
    }
   ]
  },
  {
   "title": "Reuses by context types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "si:ru/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.context as ct,\n  sum(reuses / extract(epoch from smpe.sample_time - smps.sample_time)) as \"reuses\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ct\nORDER BY time"
    }
   ]
  },
  {
   "title": "Object types I/O (based on pg_stat_io)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 }
  },
  {
   "title": "Reads by object types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.object as ot,\n  sum(reads / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Reads\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ot\nORDER BY time"
    }
   ]
  },
  {
   "title": "Read time by object types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.object as ot,\n  sum(read_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Read time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ot\nORDER BY time"
    }
   ]
  },
  {
   "title": "Reads by object types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.object as ot,\n  sum(reads / extract(epoch from smpe.sample_time - smps.sample_time)) as \"Reads\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ot\nORDER BY time"
    }
   ]
  },
  {
   "title": "Write time by object types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.object as ot,\n  sum(write_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Write time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ot\nORDER BY time"
    }
   ]
  },
  {
   "title": "Extends by object types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "e/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.object as ot,\n  sum(extends / extract(epoch from smpe.sample_time - smps.sample_time)) as \"extends\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ot\nORDER BY time"
    }
   ]
  },
  {
   "title": "Extend time by object types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.object as ot,\n  sum(write_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Write time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ot\nORDER BY time"
    }
   ]
  },
  {
   "title": "Fsyncs by object types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "fsyncs/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.object as ot,\n  sum(fsyncs / extract(epoch from smpe.sample_time - smps.sample_time)) as \"fsyncs\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ot\nORDER BY time"
    }
   ]
  },
  {
   "title": "Fsync time by object types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "s/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.object as ot,\n  sum(fsync_time / extract(epoch from smpe.sample_time - smps.sample_time))/1000 as \"Fsync time per second\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ot\nORDER BY time"
    }
   ]
  },
  {
   "title": "Hits by object types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "si:hits/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.object as ot,\n  sum(hits / extract(epoch from smpe.sample_time - smps.sample_time)) as \"hits\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ot\nORDER BY time"
    }
   ]
  },
  {
   "title": "Reuses by object types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "si:ru/s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  smpe.sample_time as time,\n  sio.object as ot,\n  sum(reuses / extract(epoch from smpe.sample_time - smps.sample_time)) as \"reuses\"\nFROM sample_stat_io sio\n  JOIN samples smpe USING (server_id, sample_id)\n  JOIN samples smps ON (smpe.server_id, smpe.sample_id -1) = (smps.server_id, smps.sample_id)\nWHERE\n  sio.server_id = ${profile_servers}\n  AND smpe.sample_id BETWEEN $startid + 1 AND $endid\nGROUP BY time, ot\nORDER BY time"
    }
   ]
  }
 ]
}