CREATE SCHEMA IF NOT EXISTS profile;
CREATE SCHEMA IF NOT EXISTS dblink;
CREATE SCHEMA IF NOT EXISTS statements;
CREATE EXTENSION dblink SCHEMA dblink;
CREATE EXTENSION pg_stat_statements SCHEMA statements;
CREATE EXTENSION pg_profile SCHEMA profile;
SELECT * FROM profile.snapshot();
SELECT * FROM profile.snapshot();
SELECT count(1) FROM profile.report(1,2);
SELECT * FROM profile.snapshot();
SELECT count(1) FROM profile.report_diff(1,2,2,3);
SELECT * FROM profile.snapshot();
SELECT * FROM profile.snapshot();
UPDATE profile.snapshots SET snap_time = now() - '4 days'::interval - '10 minutes'::interval WHERE node_id = 1 AND snap_id = 1;
UPDATE profile.snapshots SET snap_time = now() - '3 days'::interval - '10 minutes'::interval WHERE node_id = 1 AND snap_id = 2;
UPDATE profile.snapshots SET snap_time = now() - '2 days'::interval - '10 minutes'::interval WHERE node_id = 1 AND snap_id = 3;
UPDATE profile.snapshots SET snap_time = now() - '1 days'::interval - '10 minutes'::interval WHERE node_id = 1 AND snap_id = 4;
UPDATE profile.snapshots SET snap_time = now() - '23 hours'::interval - '10 minutes'::interval WHERE node_id = 1 AND snap_id = 5;
SELECT * FROM profile.snapshot();
SELECT COUNT(*) FROM profile.snapshots WHERE snap_time < now() - '1 days'::interval;
SELECT * FROM profile.node_retention('local',1);
SELECT * FROM profile.snapshot();
SELECT COUNT(*) FROM profile.snapshots WHERE snap_time < now() - '1 days'::interval;
DROP EXTENSION pg_profile;
